services:
  defaults:
    autowire: true
    public: false

  controllers:
    resource: internal/controller/
    tags: [controller]

  services:
    App\Service\UserService:
      arguments:
        $kernel: '@kernel'
